### ISSUE TITLE
Keyboard trackpad combo

### ISSUE THREAD

**Issue by KreeperSteve** [quaxalber/bluetooth_2_usb#115]
I finally got a half working keyboard connects to the pie plugged into KVM switch going to two window systems but the trackpad still not working

**Comment by quaxalber** [comment]
Hey there, 

Please post the output from: 

```console
bluetooth_2_usb -l
```

and from:

```console
sudo service bluetooth_2_usb stop && sudo bluetooth_2_usb -ad ; sudo service bluetooth_2_usb start
```

... and try to use your trackpad before cancelling with `Ctrl + C`

**Comment by KreeperSteve** [comment]
steven@stupid:~ $ bluetooth_2_usb -l
Bluetooth 5.1 Keyboard Mouse    22:21:53:e9:99:bf       /dev/input/event2
Bluetooth 5.1 Keyboard  22:21:53:e9:99:bf       /dev/input/event1
vc4-hdmi        vc4-hdmi/input0 /dev/input/event0

**Comment by KreeperSteve** [comment]
24-02-18 10:09:04 [CRITICAL] Connection to Bluetooth 5.1 Keyboard lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to vc4-hdmi lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to Bluetooth 5.1 Keyboard Mouse lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to Bluetooth 5.1 Keyboard lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to vc4-hdmi lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to Bluetooth 5.1 Keyboard Mouse lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to Bluetooth 5.1 Keyboard lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to vc4-hdmi lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to Bluetooth 5.1 Keyboard Mouse lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to Bluetooth 5.1 Keyboard lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to vc4-hdmi lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to Bluetooth 5.1 Keyboard Mouse lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to Bluetooth 5.1 Keyboard lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to vc4-hdmi lost [OSError(16, 'Device or resource busy')]
24-02-18 10:09:04 [DEBUG] Initializing USB gadgets...
24-02-18 10:09:04 [CRITICAL] Connection to Bluetooth 5.1 Keyboard Mouse lost [OSError(16, 'Device or resource busy')]




It's spitting this out really fast and not stopping

**Comment by quaxalber** [comment]
Please reboot the Pi and try the second cmd again

**Comment by KreeperSteve** [comment]
I apologize I sincerely do I kept rebooting and trying it and kept doing the same thing I'll try again later

**Comment by quaxalber** [comment]
> I apologize

No need to. 

In [this issue](https://github.com/quaxalber/bluetooth_2_usb/issues/112) the problem was resolved by a clean re-installation. Perhaps worth a try?
