### ISSUE TITLE
Long reconnection time for keyboard

### ISSUE THREAD

**Issue by cylonid** [quaxalber/bluetooth_2_usb#59]
Great lib so far. Compared to the original repo, all media keys work out of the box and mouse support is a nice addition.

What blocks me of using this as daily driver is that my keyboard takes really long (15-20s) to reconnect once the keyboard enters its standby mode (I am not talking about the delay when the Pi is rebooting). 

It does reconnect in the end, but I wonder what is taking so long. The mouse reconnects really quick on the other hand. Any insights or things I could try out? I saw there are some small delays/sleeps in there, are they strictly necessary?

**Comment by quaxalber** [comment]
Hey there, glad you enjoy the changes! 

I suspect that the delay occurs on device level. It's up to the firmware how the bluetooth advertising is implemented. The best way to check this is through `bluetoothctl`. You may observe how the devices behave in different scenarios (Pi's Bluetooth power off/on, keyboard off/on, keyboard blocked/unblocked and ultimately standby on/off). Let me know if you need any help with that. The [troubleshooting](https://github.com/quaxalber/bluetooth_2_usb#8-troubleshooting) section contains some commands that may come in handy. 

When I switch off/on Pi's Bluetooth interface, it's a matter of 1-2 seconds for the devices to be picked up again. 

> I saw there are some small delays/sleeps in there, are they strictly necessary?

Nah, they are more to take load off the Pi. Feel free to adjust. However, I doubt that these are causing these long delays. 

Which version are you running?

**Comment by ig-sinicyn** [comment]
UPD: I'd want to report same issue for the v0.6.6.
I have indicator on the keyboard that shows connection status. On older versions (mid-november ones) and on windows the input is received exactly at the moment the keyboard shows connection is succeed. With the 0.6.6 there's noticeable delay (2-3 seconds or so) between actual connection and input receiving.

**Comment by quaxalber** [comment]
> there's noticeable delay (2-3 seconds or so) between actual connection and input receiving.

I can confirm a delay in that magnitude for each device upon connection. Requires investigation. If you have a clue please let me know!

**Comment by ig-sinicyn** [comment]
Have no good idea, sorry:( 
I've tryed to reduce sleep timeout in the 
```
await asyncio.sleep(2)
```
https://github.com/quaxalber/bluetooth_2_usb/blob/main/src/bluetooth_2_usb/relay.py#L219C13-L219C35.
It helped but not a lot.

**Comment by cylonid** [comment]
> await asyncio.sleep(2)

If I understood @quaksalber correctly, then this only sets the interval between reconnection attempts. So yes, reducing this number will naturally decrease the whole reconnection time, but it is unlikely to be the real culprit.

I didn't find time yet to do further investigations as advised here with running in debug mode and looking into the reconnection time from input device and Pi as proxy, but I hope to do that within the week.

My concern is that I really may be due to the subpar BT chip performance on the Pi Zero. After all, it's already struggling to keep up WiFi and BT at the same time, which is why I disabled WiFi as one of my first measures before even setting up this project.

**Comment by quaxalber** [comment]
Found and arrested the culprit. Should be fixed in [v0.6.7](https://github.com/quaxalber/bluetooth_2_usb/releases/tag/v0.6.7) - would appreciate any feedback from you guys. 

For details see PR #84

Thank you both!

**Comment by ig-sinicyn** [comment]
@quaxalber , thanks a lot!

I can confirm the issue is resolved and connection time is pretty much the same as when connecting directly to PC.

**Comment by quaxalber** [comment]
Great stuff! Thx for letting us know 

@cylonid Does it resolve your issues as well?

**Comment by cylonid** [comment]
@quaxalber Sorry, had no access to the setup over the holidays. Now I can confirm it's working nicely, thank you. 
The delay is down to the usual delay for BT keyboards, tested on Windows, Ubuntu and Android 🎉 

With my setup (I use two USB cables, one for permanent power connection and the second data-only cable for connection to PC) it is even possible to switch the target devices without rebooting the Pi.
